name: Qt Project Build Workflow

on:
    push:
        branches: "**"
    pull_request:
        branches:
            - main

jobs:
    build:
        name: Build on Windows
        runs-on: windows-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install Qt
              uses: jurplel/install-qt-action@v3
              with:
                  aqtversion: "==3.1.*"
                  version: "5.9.9"
                  host: "windows"
                  target: "desktop"
                  arch: "win32_mingw53"

            - name: Build Project
              run: |
                  qmake Nautica.pro
                  "${{ env.Qt5_Dir }}/bin/mingw32-make"
                  "${{ env.Qt5_Dir }}/bin/mingw32-make clean"
