name: Qt Project Build Workflow

on:
    push:
        branches: "**"
    pull_request:
        branches:
            - main

jobs:
    build:
        name: Build on Windows
        runs-on: windows-latest
        env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: true
            QtInstallDir: ${{ github.workspace }}/Qt/5.9.9/mingw53_32
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Install Qt
              uses: jurplel/install-qt-action@v3
              with:
                  aqtversion: "==3.1.*"
                  version: "5.9.9"
                  host: "windows"
                  target: "desktop"
                  arch: "win32_mingw53"

            - name: Setup Qt environment
              shell: cmd
              run: |
                  echo ::add-path::${{ env.QtInstallDir }}/bin
                  echo ::add-path::${{ env.QtInstallDir }}/lib
                  echo ::add-path::${{ env.QtInstallDir }}/qml
                  echo ::add-path::${{ env.QtInstallDir }}/plugins

            - name: Build Project
              run: |
                  qmake Nautica.pro
                  ${{ env.QtInstallDir }}/bin/mingw32-make
                  ${{ env.QtInstallDir }}/bin/mingw32-make clean
