name: Clang-Format

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Clang
        run: |
          sudo apt update
          sudo apt install -y clang-format

      - name: Run Clang-Format
        run: |
          clang-format -style=llvm -i *.cpp *.h
